# **Data Cleaning**

In [1]:
#import modules
import pandas as pd

In [2]:
#upload the file
from google.colab import files
uploaded = files.upload()

Saving global_ecommerce_sales.csv to global_ecommerce_sales.csv

In [3]:
#save on a dataframe
df = pd.read_csv('global_ecommerce_sales.csv')
df

,Order_ID,Country,Category,Unit_Price,Quantity,Order_Date,Total_Amount
0,1,Germany,Electronics,285.82,7,6/12/2025,2000.74
1,2,Pakistan,Toys,132.00,9,1/14/2025,1188.00
2,3,Australia,Fashion,481.65,9,8/27/2025,4334.85
3,4,UAE,Grocery,244.36,3,3/13/2025,733.08
4,5,Germany,Sports,403.97,5,5/23/2025,2019.85
...,...,...,...,...,...,...,...
1195,1196,China,Sports,274.52,6,6/3/2025,1647.12
1196,1197,Canada,Sports,481.57,1,2/4/2025,481.57
1197,1198,UK,Sports,42.42,6,3/20/2025,254.52
1198,1199,USA,Books,186.01,1,3/8/2025,186.01
1199,1200,UAE,Electronics,116.56,6,2/3/2025,699.36

In [4]:
#check column and data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      1200 non-null   int64
 1   Country       1200 non-null   object
 2   Category      1200 non-null   object
 3   Unit_Price    1200 non-null   float64
 4   Quantity      1200 non-null   int64
 5   Order_Date    1200 non-null   object
 6   Total_Amount  1200 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 65.8+ KB

In [5]:
#change column names into snake case format
df.columns = df.columns.str.lower().str.replace(' ', '_')
df

,order_id,country,category,unit_price,quantity,order_date,total_amount
0,1,Germany,Electronics,285.82,7,6/12/2025,2000.74
1,2,Pakistan,Toys,132.00,9,1/14/2025,1188.00
2,3,Australia,Fashion,481.65,9,8/27/2025,4334.85
3,4,UAE,Grocery,244.36,3,3/13/2025,733.08
4,5,Germany,Sports,403.97,5,5/23/2025,2019.85
...,...,...,...,...,...,...,...
1195,1196,China,Sports,274.52,6,6/3/2025,1647.12
1196,1197,Canada,Sports,481.57,1,2/4/2025,481.57
1197,1198,UK,Sports,42.42,6,3/20/2025,254.52
1198,1199,USA,Books,186.01,1,3/8/2025,186.01
1199,1200,UAE,Electronics,116.56,6,2/3/2025,699.36

In [6]:
#change order_date format and remove all november transactions
df['order_date'] = pd.to_datetime(df['order_date'])
df = df[df['order_date'].dt.month != 11]
display(df)

,order_id,country,category,unit_price,quantity,order_date,total_amount
0,1,Germany,Electronics,285.82,7,2025-06-12,2000.74
1,2,Pakistan,Toys,132.00,9,2025-01-14,1188.00
2,3,Australia,Fashion,481.65,9,2025-08-27,4334.85
3,4,UAE,Grocery,244.36,3,2025-03-13,733.08
4,5,Germany,Sports,403.97,5,2025-05-23,2019.85
...,...,...,...,...,...,...,...
1195,1196,China,Sports,274.52,6,2025-06-03,1647.12
1196,1197,Canada,Sports,481.57,1,2025-02-04,481.57
1197,1198,UK,Sports,42.42,6,2025-03-20,254.52
1198,1199,USA,Books,186.01,1,2025-03-08,186.01
1199,1200,UAE,Electronics,116.56,6,2025-02-03,699.36

In [7]:
#save into excel file
df.to_excel('global_ecommerce_sales_cleaned.xlsx', index=False)